const amqp = require('amqplib/callback_api');

amqp.connect('amqp://localhost', (connError, conn) => {
  if (connError) {
    throw connError;
  }

  conn.createChannel((channelError, channel) => {
    if (channelError) {
      throw channelError;
    }

    const exchange = 'logs';
    channel.assertExchange(exchange, 'fanout', { durable: true });

    // Create a non durable queue, autogenerated name
    channel.assertQueue('', { exclusive: true }, (queueError, assertQueue) => {
      if (queueError) {
        throw queueError;
      }

      channel.bindQueue(assertQueue.queue, exchange, ''); // Receive all messages

      channel.consume(assertQueue.queue, (msg) => {
        console.log('🚀 Received: ', msg.content.toString());
        channel.ack(msg);
      }, { noAck: false });
    }); 
  });
});